import type { SurahSummary } from '../types/quran';

/**
 * Metadata for all 114 surahs.
 *
 * GENERATED FILE — do not edit by hand.
 * Source: https://api.quran.com/api/v4/chapters?language=ru
 * Generated: 2026-08-13
 *
 * Every row was cross-verified against a second independent source
 * (https://api.alquran.cloud/v1/surah) with zero mismatches on `versesCount`
 * and `revelationPlace`. The ayah counts sum to 6236, the standard Hafs total.
 *
 * `showsBismillahHeader` comes from quran.com's `bismillah_pre` flag, which is
 * false for exactly two surahs: Al-Fatihah (1), where the Bismillah is ayah 1,
 * and At-Tawbah (9), which has none.
 *
 * This is metadata only — no Quran text — so it is bundled to keep surah
 * navigation instant and fully offline.
 *
 * `translatedName` is the Russian *meaning* of the name ("Открывающая Коран"),
 * not a Cyrillic transliteration of it ("Аль-Фатиха"). See notes in
 * services/quran/quranService.ts on display naming.
 */
export const SURAH_INDEX: readonly SurahSummary[] = [
  { number: 1, arabicName: "الفاتحة", transliteration: "Al-Fatihah", translatedName: "Открывающая Коран", versesCount: 7, revelationPlace: 'meccan', showsBismillahHeader: false },
  { number: 2, arabicName: "البقرة", transliteration: "Al-Baqarah", translatedName: "Корова", versesCount: 286, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 3, arabicName: "آل عمران", transliteration: "Ali 'Imran", translatedName: "Семейство Имрана", versesCount: 200, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 4, arabicName: "النساء", transliteration: "An-Nisa", translatedName: "Женщины", versesCount: 176, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 5, arabicName: "المائدة", transliteration: "Al-Ma'idah", translatedName: "Трапеза", versesCount: 120, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 6, arabicName: "الأنعام", transliteration: "Al-An'am", translatedName: "Скот", versesCount: 165, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 7, arabicName: "الأعراف", transliteration: "Al-A'raf", translatedName: "Ограды", versesCount: 206, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 8, arabicName: "الأنفال", transliteration: "Al-Anfal", translatedName: "Трофеи", versesCount: 75, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 9, arabicName: "التوبة", transliteration: "At-Tawbah", translatedName: "Покаяние", versesCount: 129, revelationPlace: 'medinan', showsBismillahHeader: false },
  { number: 10, arabicName: "يونس", transliteration: "Yunus", translatedName: "Йунус", versesCount: 109, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 11, arabicName: "هود", transliteration: "Hud", translatedName: "Худ", versesCount: 123, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 12, arabicName: "يوسف", transliteration: "Yusuf", translatedName: "Йусуф", versesCount: 111, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 13, arabicName: "الرعد", transliteration: "Ar-Ra'd", translatedName: "Гром", versesCount: 43, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 14, arabicName: "ابراهيم", transliteration: "Ibrahim", translatedName: "Ибрахим", versesCount: 52, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 15, arabicName: "الحجر", transliteration: "Al-Hijr", translatedName: "Хиджр ", versesCount: 99, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 16, arabicName: "النحل", transliteration: "An-Nahl", translatedName: "Пчелы", versesCount: 128, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 17, arabicName: "الإسراء", transliteration: "Al-Isra", translatedName: "Ночной перенос", versesCount: 111, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 18, arabicName: "الكهف", transliteration: "Al-Kahf", translatedName: "Пещера", versesCount: 110, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 19, arabicName: "مريم", transliteration: "Maryam", translatedName: "Марьям", versesCount: 98, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 20, arabicName: "طه", transliteration: "Taha", translatedName: "Та Ха ", versesCount: 135, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 21, arabicName: "الأنبياء", transliteration: "Al-Anbya", translatedName: "Пророки", versesCount: 112, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 22, arabicName: "الحج", transliteration: "Al-Hajj", translatedName: "Паломничество", versesCount: 78, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 23, arabicName: "المؤمنون", transliteration: "Al-Mu'minun", translatedName: "Верующие", versesCount: 118, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 24, arabicName: "النور", transliteration: "An-Nur", translatedName: "Свет", versesCount: 64, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 25, arabicName: "الفرقان", transliteration: "Al-Furqan", translatedName: "аль-Фуркан", versesCount: 77, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 26, arabicName: "الشعراء", transliteration: "Ash-Shu'ara", translatedName: "Поэты", versesCount: 227, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 27, arabicName: "النمل", transliteration: "An-Naml", translatedName: "Муравьи", versesCount: 93, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 28, arabicName: "القصص", transliteration: "Al-Qasas", translatedName: "Рассказ", versesCount: 88, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 29, arabicName: "العنكبوت", transliteration: "Al-'Ankabut", translatedName: "Паук", versesCount: 69, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 30, arabicName: "الروم", transliteration: "Ar-Rum", translatedName: "Римляне", versesCount: 60, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 31, arabicName: "لقمان", transliteration: "Luqman", translatedName: "Лукман", versesCount: 34, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 32, arabicName: "السجدة", transliteration: "As-Sajdah", translatedName: "Земной поклон", versesCount: 30, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 33, arabicName: "الأحزاب", transliteration: "Al-Ahzab", translatedName: "Союзники", versesCount: 73, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 34, arabicName: "سبإ", transliteration: "Saba", translatedName: "Сава", versesCount: 54, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 35, arabicName: "فاطر", transliteration: "Fatir", translatedName: "Творец", versesCount: 45, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 36, arabicName: "يس", transliteration: "Ya-Sin", translatedName: "Йа Син", versesCount: 83, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 37, arabicName: "الصافات", transliteration: "As-Saffat", translatedName: "Выстроившиеся в ряды", versesCount: 182, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 38, arabicName: "ص", transliteration: "Sad", translatedName: "Сод", versesCount: 88, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 39, arabicName: "الزمر", transliteration: "Az-Zumar", translatedName: "Толпы", versesCount: 75, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 40, arabicName: "غافر", transliteration: "Ghafir", translatedName: "Прощающий", versesCount: 85, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 41, arabicName: "فصلت", transliteration: "Fussilat", translatedName: "Разъяснены", versesCount: 54, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 42, arabicName: "الشورى", transliteration: "Ash-Shuraa", translatedName: "Совет", versesCount: 53, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 43, arabicName: "الزخرف", transliteration: "Az-Zukhruf", translatedName: "Украшения", versesCount: 89, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 44, arabicName: "الدخان", transliteration: "Ad-Dukhan", translatedName: "Дым", versesCount: 59, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 45, arabicName: "الجاثية", transliteration: "Al-Jathiyah", translatedName: "Коленопреклоненные", versesCount: 37, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 46, arabicName: "الأحقاف", transliteration: "Al-Ahqaf", translatedName: "Барханы", versesCount: 35, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 47, arabicName: "محمد", transliteration: "Muhammad", translatedName: "Мухаммад", versesCount: 38, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 48, arabicName: "الفتح", transliteration: "Al-Fath", translatedName: "Победа", versesCount: 29, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 49, arabicName: "الحجرات", transliteration: "Al-Hujurat", translatedName: "Комнаты", versesCount: 18, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 50, arabicName: "ق", transliteration: "Qaf", translatedName: "Каф", versesCount: 45, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 51, arabicName: "الذاريات", transliteration: "Adh-Dhariyat", translatedName: "Рассеивающие прах", versesCount: 60, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 52, arabicName: "الطور", transliteration: "At-Tur", translatedName: "Гора", versesCount: 49, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 53, arabicName: "النجم", transliteration: "An-Najm", translatedName: "Звезда", versesCount: 62, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 54, arabicName: "القمر", transliteration: "Al-Qamar", translatedName: "Месяц", versesCount: 55, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 55, arabicName: "الرحمن", transliteration: "Ar-Rahman", translatedName: "Милостивый", versesCount: 78, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 56, arabicName: "الواقعة", transliteration: "Al-Waqi'ah", translatedName: "Событие", versesCount: 96, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 57, arabicName: "الحديد", transliteration: "Al-Hadid", translatedName: "Железо", versesCount: 29, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 58, arabicName: "المجادلة", transliteration: "Al-Mujadila", translatedName: "Препирающаяся", versesCount: 22, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 59, arabicName: "الحشر", transliteration: "Al-Hashr", translatedName: "Сбор", versesCount: 24, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 60, arabicName: "الممتحنة", transliteration: "Al-Mumtahanah", translatedName: "Испытуемая", versesCount: 13, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 61, arabicName: "الصف", transliteration: "As-Saf", translatedName: "Ряды", versesCount: 14, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 62, arabicName: "الجمعة", transliteration: "Al-Jumu'ah", translatedName: "Собрание", versesCount: 11, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 63, arabicName: "المنافقون", transliteration: "Al-Munafiqun", translatedName: "Лицемеры", versesCount: 11, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 64, arabicName: "التغابن", transliteration: "At-Taghabun", translatedName: "Взаимное обделение", versesCount: 18, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 65, arabicName: "الطلاق", transliteration: "At-Talaq", translatedName: "Развод", versesCount: 12, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 66, arabicName: "التحريم", transliteration: "At-Tahrim", translatedName: "Запрещение", versesCount: 12, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 67, arabicName: "الملك", transliteration: "Al-Mulk", translatedName: "Власть", versesCount: 30, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 68, arabicName: "القلم", transliteration: "Al-Qalam", translatedName: "Письменная трость", versesCount: 52, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 69, arabicName: "الحاقة", transliteration: "Al-Haqqah", translatedName: "Неминуемое", versesCount: 52, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 70, arabicName: "المعارج", transliteration: "Al-Ma'arij", translatedName: "Ступени", versesCount: 44, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 71, arabicName: "نوح", transliteration: "Nuh", translatedName: "Нух", versesCount: 28, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 72, arabicName: "الجن", transliteration: "Al-Jinn", translatedName: "Джинны", versesCount: 28, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 73, arabicName: "المزمل", transliteration: "Al-Muzzammil", translatedName: "Закутавшийся", versesCount: 20, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 74, arabicName: "المدثر", transliteration: "Al-Muddaththir", translatedName: "Завернувшийся", versesCount: 56, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 75, arabicName: "القيامة", transliteration: "Al-Qiyamah", translatedName: "Воскресение", versesCount: 40, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 76, arabicName: "الانسان", transliteration: "Al-Insan", translatedName: "Человек", versesCount: 31, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 77, arabicName: "المرسلات", transliteration: "Al-Mursalat", translatedName: "Посылаемые", versesCount: 50, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 78, arabicName: "النبإ", transliteration: "An-Naba", translatedName: "Весть", versesCount: 40, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 79, arabicName: "النازعات", transliteration: "An-Nazi'at", translatedName: "Исторгающие", versesCount: 46, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 80, arabicName: "عبس", transliteration: "'Abasa", translatedName: "Нахмурился", versesCount: 42, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 81, arabicName: "التكوير", transliteration: "At-Takwir", translatedName: "Скручивание", versesCount: 29, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 82, arabicName: "الإنفطار", transliteration: "Al-Infitar", translatedName: "Раскалывание", versesCount: 19, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 83, arabicName: "المطففين", transliteration: "Al-Mutaffifin", translatedName: "Обвешивающие", versesCount: 36, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 84, arabicName: "الإنشقاق", transliteration: "Al-Inshiqaq", translatedName: "Разверзнется", versesCount: 25, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 85, arabicName: "البروج", transliteration: "Al-Buruj", translatedName: "Созвездия Зодиака", versesCount: 22, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 86, arabicName: "الطارق", transliteration: "At-Tariq", translatedName: "Ночной путник", versesCount: 17, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 87, arabicName: "الأعلى", transliteration: "Al-A'la", translatedName: "Всевышний", versesCount: 19, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 88, arabicName: "الغاشية", transliteration: "Al-Ghashiyah", translatedName: "Покрывающее", versesCount: 26, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 89, arabicName: "الفجر", transliteration: "Al-Fajr", translatedName: "Заря", versesCount: 30, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 90, arabicName: "البلد", transliteration: "Al-Balad", translatedName: "Город", versesCount: 20, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 91, arabicName: "الشمس", transliteration: "Ash-Shams", translatedName: "Солнце", versesCount: 15, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 92, arabicName: "الليل", transliteration: "Al-Layl", translatedName: "Ночь", versesCount: 21, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 93, arabicName: "الضحى", transliteration: "Ad-Duhaa", translatedName: "Утро", versesCount: 11, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 94, arabicName: "الشرح", transliteration: "Ash-Sharh", translatedName: "Раскрытие", versesCount: 8, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 95, arabicName: "التين", transliteration: "At-Tin", translatedName: "Смоковница", versesCount: 8, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 96, arabicName: "العلق", transliteration: "Al-'Alaq", translatedName: "Сгусток крови", versesCount: 19, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 97, arabicName: "القدر", transliteration: "Al-Qadr", translatedName: "Предопределение", versesCount: 5, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 98, arabicName: "البينة", transliteration: "Al-Bayyinah", translatedName: "Ясное знамение", versesCount: 8, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 99, arabicName: "الزلزلة", transliteration: "Az-Zalzalah", translatedName: "Сотрясение", versesCount: 8, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 100, arabicName: "العاديات", transliteration: "Al-'Adiyat", translatedName: "Скачущие", versesCount: 11, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 101, arabicName: "القارعة", transliteration: "Al-Qari'ah", translatedName: "Великое бедствие", versesCount: 11, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 102, arabicName: "التكاثر", transliteration: "At-Takathur", translatedName: "Страсть к приумножению", versesCount: 8, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 103, arabicName: "العصر", transliteration: "Al-'Asr", translatedName: "Предвечернее время", versesCount: 3, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 104, arabicName: "الهمزة", transliteration: "Al-Humazah", translatedName: "Хулитель", versesCount: 9, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 105, arabicName: "الفيل", transliteration: "Al-Fil", translatedName: "Слон", versesCount: 5, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 106, arabicName: "قريش", transliteration: "Quraysh", translatedName: "Курейшиты", versesCount: 4, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 107, arabicName: "الماعون", transliteration: "Al-Ma'un", translatedName: "Мелочь", versesCount: 7, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 108, arabicName: "الكوثر", transliteration: "Al-Kawthar", translatedName: "Изобилие", versesCount: 3, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 109, arabicName: "الكافرون", transliteration: "Al-Kafirun", translatedName: "Неверующие", versesCount: 6, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 110, arabicName: "النصر", transliteration: "An-Nasr", translatedName: "Помощь", versesCount: 3, revelationPlace: 'medinan', showsBismillahHeader: true },
  { number: 111, arabicName: "المسد", transliteration: "Al-Masad", translatedName: "Пальмовые волокна", versesCount: 5, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 112, arabicName: "الإخلاص", transliteration: "Al-Ikhlas", translatedName: "Очищение веры", versesCount: 4, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 113, arabicName: "الفلق", transliteration: "Al-Falaq", translatedName: "Рассвет", versesCount: 5, revelationPlace: 'meccan', showsBismillahHeader: true },
  { number: 114, arabicName: "الناس", transliteration: "An-Nas", translatedName: "Люди", versesCount: 6, revelationPlace: 'meccan', showsBismillahHeader: true },
];
